---
- name: Destroy Infrastructure
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Retrieve EC2 instances by tag
      amazon.aws.ec2_instance_info:
        region: us-east-1
        filters:
          "tag:Name": "CI-CD-Yoram"
      register: ec2_facts

    - name: Terminate EC2 instances
      amazon.aws.ec2_instance:
        region: us-east-1
        instance_ids: "{{ ec2_facts.instances | map(attribute='instance_id') | list }}"
        state: absent
      when: ec2_facts.instances | length > 0
